### ISSUE TITLE
Familiarize yourself with how Mantine looks.

### ISSUE THREAD

**Issue by joshmanders** [aniftyco/nifty-ui#1]
Look over Mantine and the Mantine UI packages and get a feel of how they style stuff, notice how minimal and clean things are and how you can bring that over to Nifty UI.

**Comment by UsefulBroom** [comment]
This will more than likely be on-going, but Im moving it to in-progress for now.

**Comment by UsefulBroom** [comment]
Going to get this out of here, I am fairly certain I understand the styling requirements. but have it bookmarked as reference for whatever it is I'm working on.
